export const INPUT_TITLE = "INPUT_TITLE";
export const INPUT_TEXT = "INPUT_TEXT";
export const CLEAR_ADD_POST = "CLEAR_ADD_POST";

export const ADD_POST_ASYNC_REQUEST = "ADD_POST_ASYNC_REQUEST";
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const ADD_POST_FAILURE = "ADD_POST_FAILURE";
